data_dir: "/var/lib/vector"
api:
  enabled: true
  address: "0.0.0.0:8686"

sources:
  my_source_id:
    type: demo_logs
    format: json
    lines:
      - line1
sinks:
  my_sink_id:
    type: kafka
    inputs:
      - my_source_id
    bootstrap_servers: 172.16.201.31:9092,172.16.201.32:9092,172.16.201.33:9092
    encoding:
      codec: "json"
    topic: logs
