global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'consul'
    consul_sd_configs:
      - server: 'http://consul:8500'
    relabel_configs:
      # Если ServiceAddress пустой, используем адрес узла Consul
      - source_labels: [__meta_consul_service_address, __meta_consul_service_port]
        target_label: __address__
        regex: '(.*);(.*)'
        replacement: '${1}:${2}'
