version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.14.6
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./config:/etc/consul.d  # Монтируем директорию с конфигурацией
    command: agent -dev -client=0.0.0.0 -config-dir=/etc/consul.d

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - consul

  service1:
    build:
      context: ./services/service1
    ports:
      - "5001:5000"
    environment:
      - SERVICE_NAME=service1
      - SERVICE_PORT=5000
    depends_on:
      - consul

  service2:
    build:
      context: ./services/service2
    ports:
      - "5002:5000"
    environment:
      - SERVICE_NAME=service2
      - SERVICE_PORT=5000
    depends_on:
      - consul

networks:
  default:
    name: consul_network
    driver: bridge
