test:
  enabled: false
write:
  persistence:
    size: 32Gi
    storageClass: managed
read:
  persistence:
    size: 32Gi
    storageClass: managed
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
    storage:
      type: 'filesystem'
monitoring:
  selfMonitoring:
    enabled: false
    lokiCanary:
      enabled: false
gateway:
  basicAuth:
    enabled: true
    username: tando
    password: ${loki_gateway_password}
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "cert-manager-global"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: eu.loki.${domain_name}
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: loki-gateway-nginx-tls
        hosts:
          - eu.loki.${domain_name}